server {
    listen 80;
    server_name _;

    # Vue 정적 파일
    root   /usr/share/nginx/html;
    index  index.html;

    # Vue history 모드 대응
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 백엔드 API (prefix = /api)
    location /api/ {
        proxy_pass http://hopon-admin:8081;
    }
    # 관리자 백엔드 API 프록시
    # 프론트에서 axios/fetch로 /admin/... 호출한다고 가정
    location /admin/ {
        proxy_pass http://hopon-admin:8081;
    }

    location /auth/ {
        proxy_pass http://hopon-admin:8081;
    }
     
    location /inquiries/ {
        proxy_pass http://hopon-admin:8081;
    }

    location /reservations/ {
        proxy_pass http://hopon-admin:8081;
    }

    location /users/ {
        proxy_pass http://hopon-admin:8081;
    }
}
